### PR TITLE
metadata for package release

### PR DESCRIPTION
**Pull request by lalomartins**
note: I trimmed the summary field a bit, since new-style Meteor packages have a 100
character limit for that field.

I tested it by publishing it as lalomartins:mongodb-server-aggregation (and then unpublishing that).

### CODE REVIEW

**Comment by zvictor** [comment]
Very nice!
Let me try to publish it now. Thank you =)

**Comment by zvictor** [comment]
it has been posted and can be found at https://atmospherejs.com/zvictor/mongodb-server-aggregation
it's the first time I did it and I received the following warning. should we do something about it?

``` haskell
WARNING: Your package contains binary code and is only compatible with os.linux.x86_64 architecture.
Please use publish-for-arch to publish new builds of the package.
```

**Comment by lalomartins** [comment]
I got that warning too. With some investigation, I found it's because we're including the mongodb package via npm. The warning is correct and there's no problem there.

_If_ you want to support development on Mac (I hear tons of developers use that), I can `publish-for-arch` from my hackintosh VM for you. You just need to give me maintainer access with `meteor admin maintainers zvictor:mongodb-server-aggregation --add lalomartins`

**Comment by zvictor** [comment]
It's done!
I have added you as collaborator here as well, so you can accept PRs and make changes directly to this package. As you have already made good collaborations and is showing commitment to this project, I believe you deserve our trust =)

**Comment by lalomartins** [comment]
thanks!

**Pull request merged**
